mod dangle;
mod experimenter01;
mod first_word;
mod looper;
mod loopmania;
mod mutabex;
mod mutatext;
mod mutcomplex;
mod rata;
mod struct02;
mod usizer;
use dangle::dangle;
use dangle::dangles;
use experimenter01::display_vec_position_value;
use experimenter01::experimenter01;
use first_word::first_word;
use looper::looper;
use loopmania::loopmania;
use mutabex::mutabex;
use mutatext::mutatext;
use mutcomplex::mutcomplex;
use rata::rata;
use rata::run;
use struct02::*;
use usizer::*;
// use loopmania::*;

fn main() {
    let stern = String::from("Rust Models");
    println!("loopmania start");
    loopmania();
    looper();
    mutcomplex();
    mutabex();
    mutatext();
    dangle();
    usizer();
    experimenter01();
    first_word(&stern);
    rata();
    struct02();
}
